// lib/dados/servicosPadrao.ts

import type { Servico } from '@/lib/tipos/servico'

const agora = '2026-01-01T00:00:00.000Z'

export const servicosPadrao: Servico[] = [
  {
    id: 'serv_padrao_reboco_interno',
    nome: 'Reboco interno',
    categoria: 'reboco',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_reboco_externo',
    nome: 'Reboco externo',
    categoria: 'reboco',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_contrapiso',
    nome: 'Contrapiso',
    categoria: 'pisos',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'piso',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_regularizacao',
    nome: 'Regularização',
    categoria: 'pisos',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'piso',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_piso',
    nome: 'Piso',
    categoria: 'pisos',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'piso',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_rodape',
    nome: 'Rodapé',
    categoria: 'pisos',
    unidade: 'm',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'comprimento_linear',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_revestimento_parede',
    nome: 'Revestimento parede',
    categoria: 'revestimentos',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_pintura_parede',
    nome: 'Pintura parede',
    categoria: 'pintura',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_elevacao_muro',
    nome: 'Elevação de muro',
    categoria: 'muros',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_reboco_muro',
    nome: 'Reboco de muro',
    categoria: 'muros',
    unidade: 'm2',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'parede',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_porta',
    nome: 'Porta',
    categoria: 'acabamentos',
    unidade: 'un',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'item_unitario',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_janela',
    nome: 'Janela',
    categoria: 'acabamentos',
    unidade: 'un',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'item_unitario',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_vaso_sanitario',
    nome: 'Vaso sanitário',
    categoria: 'acabamentos',
    unidade: 'un',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'item_unitario',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_instalacoes_eletricas',
    nome: 'Instalações elétricas',
    categoria: 'instalacoes',
    unidade: 'verba',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'valor_manual',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_hidrossanitarias',
    nome: 'Hidrossanitárias',
    categoria: 'instalacoes',
    unidade: 'verba',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'valor_manual',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
  {
    id: 'serv_padrao_limpeza_final',
    nome: 'Limpeza final',
    categoria: 'complementacao',
    unidade: 'verba',
    valorUnitarioPadrao: 0,
    tipoCalculo: 'valor_manual',
    usaBdi: true,
    ativo: true,
    criadoEm: agora,
    atualizadoEm: agora,
  },
]